### ISSUE TITLE
[feature request] add metadata to junit xml as property tags

### ISSUE THREAD

**Issue by timsampsoncujo** [pytest-dev/pytest-metadata#16]
I was kind of expecting any metadata to wind up as a property tag in the junitxml but apparently this isn't the case?

**Comment by BeyondEvil** [comment]
Hi @timsampsoncujo!

Thanks for your report!

What made you expect to see metadata as a property tag in junitxml? 🤔 

I'm happy to review a PR adding that functionality as a command line flag.

Cheers!

**Comment by timsampsoncujo** [comment]
Sorry, upon rereading, I think my report was possibly a bit blunt. To rephrase in a hopefully less presumptous way.....

My understanding of the junit spec is such that property tags are used for storing arbitrary metadata regarding the tests therein. That being the case, it would seem useful to have the metadata defined by this plugin dropped in there? If you agree I could take a look a putting up a PR

**Comment by nicoddemus** [comment]
Hi everyone, just wanted to mention that [`record_property`](https://docs.pytest.org/en/latest/reference.html#record-property) can be used for this exact purpose. 👍

**Comment by timsampsoncujo** [comment]
Sure, that's what I ended up using actually. But I guess the metadata plugin could hook into that also?

**Comment by nicoddemus** [comment]
> But I guess the metadata plugin could hook into that also?

Oh sorry, yes, that's what I meant: `pytest-metadata` could be updated to use that fixture to add properties to junitxml automatically.

**Comment by BeyondEvil** [comment]
@timsampsoncujo Looking forward to your PR. 😃  👍

**Comment by BeyondEvil** [comment]
Hey @timsampsoncujo!

Any updates on this? :)

**Comment by timsampsoncujo** [comment]
Not so far, sorry. I haven't looked into the code but I guess that this shouldn't be terribly difficult, I've just been busy lately. I'll take a look in the near future (for some definition of "near"). If someone beats me to it, no worries

**Comment by BeyondEvil** [comment]
No worries @timsampsoncujo ! Let's leave it open for now and hope you get a chance to look at it. :)

**Comment by BeyondEvil** [comment]
Any news @timsampsoncujo ? 😊

**Comment by BeyondEvil** [comment]
Closing this as stale.
