### ISSUE TITLE
[feature request] Be able to add metadata with OOP structure of tests(Class based).

### ISSUE THREAD

**Issue by veso-markov** [pytest-dev/pytest-metadata#17]

**Comment by BeyondEvil** [comment]
Hi @veso-markov !

I'm not sure exactly what you're requesting. Would you mind giving me a clear and concise example? Maybe a use-case?

Or even better, your very own PR! 😊 

Thanks!

**Comment by BeyondEvil** [comment]
@veso-markov Ping! :)

**Comment by veso-markov** [comment]
@BeyondEvil I was able to overcome the issue and I will add a  PR once I have some spare time.

**Comment by BeyondEvil** [comment]
Great! Looking forward to it, @veso-markov :)

**Comment by BeyondEvil** [comment]
Any updates on this @veso-markov ? :)

**Comment by BeyondEvil** [comment]
I'm closing this as "unclear", as the request is missing details and interaction. Feel free to reopen with more details.
