### ISSUE TITLE
Accept Metadata as JSON String

### ISSUE THREAD

**Issue by ImXron** [pytest-dev/pytest-metadata#22]
Hi!

Thanks for this great project!

Would the maintainers be interested in supporting an additional command line arg to support metadata being passed in as a JSON string? Something like:
```--metadata-json '{"cat_says": "meow"}'```?

My team and I have a use case where we have lots of metadata to pass in and want to avoid dozens of ```--metadata``` args.

I'm happy to submit a PR if so.

Thanks!

**Comment by ImXron** [comment]
Just checking in on this.

Thanks!

**Comment by symonk** [comment]
@ImXron feel free to open a PR :) 

```python
def pytest_addoption(parser):
    parser.addoption(
        "--metadata",
        action="append",
        default=[],
        dest="metadata",
        metavar=("key", "value"),
        nargs=2,
        help="additional metadata.",
    )
```

is what exists presently, sounds like a good idea to expand

**Comment by BeyondEvil** [comment]
I'm happy to review a PR @ImXron !

**Comment by ImXron** [comment]
> @ImXron feel free to open a PR :)
> 
> ```python
> def pytest_addoption(parser):
>     parser.addoption(
>         "--metadata",
>         action="append",
>         default=[],
>         dest="metadata",
>         metavar=("key", "value"),
>         nargs=2,
>         help="additional metadata.",
>     )
> ```
> 
> is what exists presently, sounds like a good idea to expand

Thanks for the response! I can try to expand that existing option this if that's preferred?
 
> I'm happy to review a PR @ImXron !

Awesome, I should have something by the end of the weekend. Thanks!

**Comment by BeyondEvil** [comment]
> I can try to expand that existing option this if that's preferred?

Actually, I would prefer to have an explicit `--metatdata-as-json` option (like you suggested).

This way we'll follow [The Zen of Python](https://legacy.python.org/dev/peps/pep-0020/) 😊 

@ImXron

**Comment by ImXron** [comment]
> > I can try to expand that existing option this if that's preferred?
> 
> Actually, I would prefer to have an explicit `--metatdata-from-json` option (like you suggested).
> 
> This way we'll follow [The Zen of Python](https://legacy.python.org/dev/peps/pep-0020/) 
> 
> @ImXron

Love it. Will do!

Thanks!
