### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by cc-stjm** [pytest-dev/pytest-metadata#23]
There hasn't been a release for a while - it'd be great to have an official release that contained https://github.com/pytest-dev/pytest-metadata/pull/18

**Comment by BeyondEvil** [comment]
Yes, I'm waiting on a PR, and then I can do a release.

**Comment by ImXron** [comment]
> There hasn't been a release for a while - it'd be great to have an official release that contained #18

@cc-stjm looks like @BeyondEvil made the release: https://github.com/pytest-dev/pytest-metadata/releases/tag/v1.9.0

If that resolves this issue, feel free to close this out. Thanks!

**Comment by cc-stjm** [comment]
Thanks, have confirmed this works for me
