### ISSUE TITLE
Setting metadata during pytest_unconfigure results in a `KeyError` when read

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest-metadata#33]
Hello!

I am trying to set metadata during `pytest_unconfigure` as so:
```
def pytest_unconfigure(config):
    config._metadata["foo"] = "bar"
```

When I print out the metadata in my code, I see the new key/value pair is there:
```
{
	'Python': '3.6.9', 
	'Platform': 'Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic', 
	'Packages': {'pytest': '6.1.2', 'py': '1.9.0', 'pluggy': '0.13.1'}, 
	'Plugins': {'rerunfailures': '9.1.1', 'metadata': '1.10.0', 'html': '3.0.1.dev11'}, 
	'foo': 'bar'
}
```

However, when I try and access it I get a `KeyError`:
```
assert config._metadata['foo'] == 'bar'
KeyError: 'foo'
```

Is it not possible to set metadata during `pytest_unconfigure`? If not, is there any way we can allow for this?

**Comment by BeyondEvil** [comment]
Looks like it's not possible. What's the use-case for setting metadata during unconfigure? 🤔

**Comment by gnikonorov** [comment]
This is one use case: https://github.com/pytest-dev/pytest-html/issues/373

Since we use this plugin for the environment table, it would be a lot easier to just have this plugin allow modification during `pytest_unconfigure`. Otherwise, we'd have to have a special field that users would have to populate which I think would be confusing, since we tell plugin users to set metadata as per https://github.com/pytest-dev/pytest-html#environment.

Besides, I think it makes sense since `pytest_unconfigure` is still part of the test run as per https://docs.pytest.org/en/stable/reference.html#pytest.hookspec.pytest_unconfigure

**Comment by BeyondEvil** [comment]
I can probably add this functionality today. Should be easy. 😊

**Comment by gnikonorov** [comment]
> I can probably add this functionality today. Should be easy. 😊 

Thank you @BeyondEvil!

**Comment by BeyondEvil** [comment]
Where (at what point under the pytest lifecycle) do you print it and see it there and where do you try to access it? @gnikonorov

**Comment by gnikonorov** [comment]
Thanks for clarifying, @BeyondEvil !
