### ISSUE TITLE
[feature] ability to hide metadata from terminal while using verbose

### ISSUE THREAD

**Issue by Tbruno25** [pytest-dev/pytest-metadata#35]
In our CI pipeline we want to collect metadata for the html report but have it hidden from the terminal output when using `-v`. 

An optional flag like `--hide-metadata` would be ideal. I'd be happy to submit a PR if the community thinks it's worth adding.

**Comment by BeyondEvil** [comment]
I wonder if that flag then belongs in the `pytest-html` plugin?

**Comment by BeyondEvil** [comment]
Closing as stale.

Feel free to reopen here or at `pytest-html`.
