### ISSUE TITLE
2.0.0: Tests not available in sdist tarball on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [pytest-dev/pytest-metadata#42]
Hi! When trying to package 2.0.0 for Arch Linux I tried to run the tests against it (this works with sdist tarballs for 1.x.x).
Unfortunately the tests directory is now missing in the tarballs on pypi.org which does not allow downstreams to run tests anymore.

It would be really great if you could add them back! Thanks!

It seems poetry is used (somewhat) for working on this project. The "packages" setting can be used for adding files only to the sdist tarball: https://python-poetry.org/docs/pyproject/#packages

**Comment by BeyondEvil** [comment]
Thanks for reporting! Yeah, I'm trying to understand the impact moving to Poetry might have.

I haven't (on purposed anyway) removed anything, so not sure how to make sure they're available in the sdist tarballs.

Any guidance is most welcome. 🙇

**Comment by BeyondEvil** [comment]
@dvzrv 

Do you mind trying the version I uploaded to test.pypi?

https://test.pypi.org/project/pytest-metadata/2.0.1rc2/

**Comment by dvzrv** [comment]
@BeyondEvil hey! Thanks for looking into this.

I am currently on holidays and can only really get back to this in early April.

Judging from the contents of the uploaded sdist tarball the test files are now included and this should work as intended though!

**Comment by BeyondEvil** [comment]
Appreciate it!

Enjoy the holiday!

And do reopen this if you run into any issues. 🙇

**Comment by BeyondEvil** [comment]
Should be fixed in 2.0.1. Thanks! 🙏
