### ISSUE TITLE
Remove python<3.11 time-bomb from project metadata

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-metadata#49]
The last release from https://pypi.org/project/pytest-metadata/ does clearly states `Requires: Python >=3.7.0, <3.11.0` in its metadata, regardless the fact that I was not able to see that in code from main branch.

That acts like a time-bomb which prevents installation of 2.0.1 on py311. I discovered this problem while trying to add py311 testing pipelines for other projects.

Interestingly, what happens is that pip picks 2.0.0 which does not have this in its metadata.

That bug should be treated as critical because it will prevent anyone using this pytest plugin from adding a py311 testping pipeline.

**Comment by ssbarnea** [comment]
@BeyondEvil Sorry to nag you about this but I do not have experience with poetry and I have the impression that this regression was caused by your decision to [Go all in pyproject.toml and poetry](https://github.com/pytest-dev/pytest-metadata/pull/43)

my impression is t

**Comment by BeyondEvil** [comment]
👀

**Comment by ssbarnea** [comment]
You only need to release main to fix it, it was fixed by you in march.

**Comment by BeyondEvil** [comment]
https://github.com/pytest-dev/pytest-metadata/pull/50 @ssbarnea

**Comment by BeyondEvil** [comment]
v2.0.2 released! 🥳
