### ISSUE TITLE
Orgranize pytest arguments into a non-custom group

### ISSUE THREAD

**Issue by xmuskrat** [pytest-dev/pytest-metadata#62]
Pytest arguments are currently added to the custom arguments group using parser.addoption.

You can organize these into a pytest-metadata group so it's clear what options go with this module.

```
grouped_options = parser.getgroup("pytest-metadata")
grouped_options.addoption 
```

This improves formatting in pytest --help

**Comment by BeyondEvil** [comment]
Thanks, will do that!
