### ISSUE TITLE
Backward compatibility issue using `config._metadata`

### ISSUE THREAD

**Issue by yoshigev** [pytest-dev/pytest-metadata#70]
Hi,

Up until version 3.0.0, the documentation stated that the metadata could be accessed from a plugin using the following code:

```python
   config._metadata['foo'] = 'bar'
```

Now, using the above code results in an error: `AttributeError: 'Config' object has no attribute '_metadata'`.

I saw that the release notes of 3.0.0 states "Use pytest.stash **internally** instead of _metadata".
I don't thinks such a change is an internal one...

Can backward compatibility be maintained somehow?

Thanks,
Yehoshua

**Comment by BeyondEvil** [comment]
Here's an example of how you can access the metadata:

```python
def pytest_configure(config):
  metadata = config.pluginmanager.getplugin("metadata")
  if metadata:
      from pytest_metadata.plugin import metadata_key
      config.stash[metadata_key]['foo'] = 'bar'
```

**Comment by eformo** [comment]
I ran into a similar issue.

in my build process i create a Docker container using `FROM python:3.9.15-slim-bullseye`

at some point during last Sunday, one of the underlying packages in that container was updated and pulled in the latest pytest-metadata version.  The workaround for me was to update my requirements.txt to pin pytest-metadata==2.0.4

I don't have pytest-metadata pinned, so the following functionality broke for me:

in my test framework in conftest.py I have the following:
```python
def pytest_addoption(parser):
    """Adds ability to get custom pytest command line arguments"""
    # General options
    parser.addoption(
        "--ci_env",
        action="store",
        default="stg",
        help="env: what env we are attaching to for testing",
    )
    parser.addoption(
        "--api_timeout",
        action="store",
        default="60",
        help="Sets API timeout.",
    )
```
Any of the options in pytest_addoption later get set as environment variables through the following code:
```python
def set_global_os_variables(config):
terminal_config_options = config._parser._anonymous.options[2:]  # pylint: disable=protected-access

    for value in terminal_config_options:
        options_in_config = value._long_opts[0]  # pylint: disable=protected-access
        os_value = config.getoption(options_in_config)
        if os_value:
            os_keyword = options_in_config.rsplit("-", 1)[1].upper()
            os.environ[os_keyword] = str(os_value).lower()
```
CI_ENV was not found, but API_TIMEOUT was.

I will look at using `config.stash` instead to fix the issue.

**Comment by bclouser** [comment]
is using config.stash backwards compatible though? Or was it only introduced in 3.x?

**Comment by BeyondEvil** [comment]
> is using config.stash backwards compatible though? Or was it only introduced in 3.x?

It was introduced in 3.0.0.

**Comment by fenchu** [comment]
You can just create it:
```
    if not hasattr(request.config, '_metadata'):
        request.config._metadata = {}
```

**Comment by rajeshkz** [comment]
> 

Why was config._metadata removed?  The way mentioned here [https://github.com/pytest-dev/pytest-metadata/issues/70#issuecomment-1567511677](here) is not intuitive. Preferably we should maintain backward compatibility.  A lot of external documentations, blogpost and how-to documents the config._metadata way of configuration.

**Comment by BeyondEvil** [comment]
> > 
> 
> Why was config._metadata removed? The way mentioned here [https://github.com/pytest-dev/pytest-metadata/issues/70#issuecomment-1567511677](here) is not intuitive. Preferably we should maintain backward compatibility. A lot of external documentations, blogpost and how-to documents the config._metadata way of configuration.

Because modifying an object like `config` with arbitrary attributes is bad. At the time this was implemented, there was no better way. That exists today with `pytest.Stash`.

If code couldn't be changed/refactored because the existence of blog posts that mention the legacy way - code would never change. This is why we have major releases with the possibility of breaking changes. What matters is the documentation for said code. If you've found and issue with that - please report it or even better - create a PR.

None of the behavioural logic has changed since `2.0.4`, so you can keep using that version.

Regardless, using Stash (or previously `_metadata`) is and should be a last resort. The fixture and hook are the preferred way.

If that for some reason isn't possible in your implementation, I'm happy to look at an example to see if there are other ways.
