### ISSUE TITLE
Environment table not showing on html report anymore

### ISSUE THREAD

**Issue by joancarrio-analog** [pytest-dev/pytest-metadata#71]
Since 3.0.0 I could not see the metadata table in the html report, even though without accessing any of the hooks.
There might be a problem with the metadata and I don't know if it could be related with the issue of '_metadata' object not being acessed.

Thanks,
Joan.

**Comment by BeyondEvil** [comment]
Closing this as a duplicate of: https://github.com/pytest-dev/pytest-html/issues/683
