### ISSUE TITLE
AttributeError: module 'pytest' has no attribute 'StashKey'

### ISSUE THREAD

**Issue by jupe** [pytest-dev/pytest-metadata#72]
File "/usr/local/lib/python3.10/site-packages/pytest_metadata/plugin.py", line 34, in <module>
    metadata_key = pytest.StashKey[dict]()
AttributeError: module 'pytest' has no attribute 'StashKey'

version: pytest_metadata-3.0.0-py3-none-any.whl

**Comment by BeyondEvil** [comment]
What pytest version are you using?

The minimal compatible version is [7.0.0](https://github.com/pytest-dev/pytest-metadata/blob/master/pyproject.toml#L43)

Supported was added here: https://github.com/pytest-dev/pytest/pull/8920

**Comment by jupe** [comment]
That’s the case. I was using pytest 6.x. Consider update readme and requirements to avoid similar confusion later :).

**Comment by BeyondEvil** [comment]
> That’s the case. I was using pytest 6.x. Consider update readme and requirements to avoid similar confusion later :).

I linked you to the (updated) requirements: https://github.com/pytest-dev/pytest-metadata/blob/master/pyproject.toml#L43

No I idea how you managed to circumvent that to get a mismatch in dependencies (old `pip` version?).
