### ISSUE TITLE
Upgrading from 2.0.4 to 3.0.0 Breaks pytest-html Integration

### ISSUE THREAD

**Issue by eightys3v3n** [pytest-dev/pytest-metadata#75]
# Problem
Using pytest-metadata version 3.0.0 instead of 2.0.4 breaks the integration with pytest-html; the environment metadata table disappears.

# Doing What
New poetry project.
Add pytest, pytest-html, pytest-metadata as requirements (all the latest version).
Add a couple test cases:
```python
def test():
    assert True

def test_metadata(metadata):
    assert 'metadata' in metadata['Plugins']
```
Run pytest.

# Expected Result
The environment table to appear in the HTML report.
Picture is of using pytest-metadata 2.0.4.
![image](https://github.com/pytest-dev/pytest-metadata/assets/15176881/cb0a4acb-d30d-4bc4-91d2-4ce0bccfb66d)

# Actual Result
No environment table.
![image](https://github.com/pytest-dev/pytest-metadata/assets/15176881/a471ce46-a85c-4890-9955-77c0fc3e1275)

# Workarounds
Downgrading pytest-metadata to version 2.0.4 returns the expected result.

**Comment by eightys3v3n** [comment]
Acknowledge here https://github.com/pytest-dev/pytest-html/issues/683
pytest-html will update on the next version to support the API change here.

**Comment by BeyondEvil** [comment]
Please feel free to try pytest-html==4.0.0rc5

I welcome any and all feedback!
