### ISSUE TITLE
Suppressing metadata dump in the terminal report

### ISSUE THREAD

**Issue by numirias** [pytest-dev/pytest-metadata#8]
I'm using pytest-metadata in a [plugin to create JSON reports](https://github.com/numirias/pytest-json-report/), similar to how pytest-html uses it, and someone asked for an option to suppress the metadata [dump in the terminal report](https://github.com/pytest-dev/pytest-metadata/blob/1363d9680c583d54d9a87b5d9fa5f48542f66a6c/pytest_metadata/plugin.py#L73).

Would an option for that be possible? Personally, I'd even favor an opt-in (or a configurable length limit) because any plugin which has pytest-metadata as a dependency, and potentially adds new objects with a large repr string to it, will unconditionally write all metadata to the terminal, even if not intended.

**Comment by davehunt** [comment]
Perhaps we could only report this if `--verbose` is passed? I'd be happy to review a patch for that.
